---
- hosts: all
  become: true
  tasks:
    - name: Create a variable
      set_fact:
        file_name: "sample1.txt"
        file_path: /home/ubuntu/app

    - name: Create directory in server
      file: 
        path: "{{ file_path }}"
        state: directory
      ignore_errors: true

    - name: Create a file
      file:
        path: "{{ file_path }}/{{ file_name }}"
        state: touch
      ignore_errors: true

    - name: Create directory using Shell
      shell: mkdir shell_app
      args:
        chdir: /home/ubuntu/
      register: result
      ignore_errors: true

    - name: Copy the file from Source to Destination
      copy:
        src: "{{ playbook_dir }}/hello.yml"
        dest: /home/ubuntu/shell_app
        mode: 0777

    - name: Show Result
      debug:
        var: result.stdout
      ignore_errors: true
