---
- name: Deploy JAR from Nexus to host
  hosts: all
  become: true
  vars:
    source_url: "https://github.com/yugesh-kk/sample-jenkins-app/blob/master/utils.groovy"
    destn: /home/ubuntu

  tasks:
    - name: Get URL from source to destination
      get_url:
        url: "{{ source_url }}"
        dest: "{{ destn }}"
        mode: 0775
