---
- name: Deploy JAR from Nexus to host
  hosts: all
  become: true
  vars:
    source_url1: "https://github.com/yugesh-kk/sample-jenkins-app/blob/master/utils.groovy"
    source_url2: "https://github.com/yugesh-kk/sample-jenkins-app/blob/master/Jenkinsfile_bkup12Jun"
    source_url3: "https://github.com/yugesh-kk/sample-jenkins-app/blob/master/hello.yml"
    destn: /home/ubuntu

  tasks:
    - name: Get URL from source to destination
      get_url:
        url: "{{ item }}"
        dest: "{{ destn }}"
        mode: 0775
      loop:
      - "{{ source_url1 }}"
      - "{{ source_url2 }}"
      - "{{ source_url3 }}"



    - name: Replace string in file
      replace:
        path: "{{ destn }}/utils.groovy"
        regexp: 'out'
        replace: 'in!'

    - name: Remove OpenJDK 11 packages
      apt:
        name:
          - openjdk-11-jdk*
          - openjdk-11-jre*
        state: present
        #purge: yes

    - name: Health Check
      shell: curl --request GET --url http://localhost:8080
      register: result
      until: result.stdout.find("Sample") != -1
      retries: 30
      delay: 5

    - name: Debugging
      debug:
        var: result
      
      
     
